<a href="https://colab.research.google.com/github/Rosalyn-DSAI/BDA_ICP1_A/blob/main/ICP3_Summer_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.
import numpy as np

# Generate a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(low=1, high=21, size=15)

# Print the generated vector
print(random_vector)

[ 1  7 16 17  4 18  9 11  2  2  2  1  8 10  4]


In [6]:
# 1 Reshape the array to 3 by 5
# [[ 1  7 16 17  4]
# [18  9 11  2  2]
# [ 2  1  8 10  4]]
a = np.array([[1,7,16,7,4], [18,9,11,2,2], [2,1,8,10,4]])
print (a)


[[ 1  7 16  7  4]
 [18  9 11  2  2]
 [ 2  1  8 10  4]]


In [7]:
# Alternatively
reshaped_array = random_vector.reshape(3, 5)
print(reshaped_array)

[[ 1  7 16 17  4]
 [18  9 11  2  2]
 [ 2  1  8 10  4]]


In [8]:
# 2. Print array shape.
print(reshaped_array.shape)

(3, 5)


In [9]:
# 3. Replace the max in each row by 0
max_indices = np.argmax(reshaped_array, axis=1)
reshaped_array[np.arange(reshaped_array.shape[0]), max_indices] = 0
print(reshaped_array)

[[ 1  7 16  0  4]
 [ 0  9 11  2  2]
 [ 2  1  8  0  4]]


In [4]:
# b. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer
# elements), also print the shape, type and data type of the array
import numpy as np
array_2d = np.array([[1,2,3,4], [5,6,7,8,],[9,10,11,12]], dtype=np.int32)
print(array_2d)
print(array_2d.shape)
print(array_2d.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
int32


In [5]:
# c. Write a program to compute the eigenvalues and right eigenvectors of a
# given square array given below: [[ 3 -2] [ 1 0]]
import numpy as np
array = np.array([[3,2], [1,0]])
eigenvalues, eigenvectors = np.linalg.eig(array)
print("Eigenvalues:", eigenvalues)
print("Right Eigenvectors:", eigenvectors)


Eigenvalues: [ 3.56155281 -0.56155281]
Right Eigenvectors: [[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]


In [9]:
# d. Compute the sum of the diagonal element of a given array:
# [[0 1 2]
# [3 4 5]]
import numpy as np
array = np.array([[0,1,2], [3,4,5]])
diagonal_sum = np.trace(array)
print("Sum of diagonal elements:", diagonal_sum)

Sum of diagonal elements: 4


In [12]:
# e. Write a NumPy program to create a new shape to an array without changing
# its data.

import numpy as np
array = np.array([1,2,3,4,5,6])
new_shape = (3,2)
new_shape2 = (2,3)
reshaped_array = np.reshape(array, new_shape, order='F')
reshaped_array2 = np.reshape(array, new_shape2, order= 'F')
print(reshaped_array)
print(reshaped_array2)

[[1 4]
 [2 5]
 [3 6]]
[[1 3 5]
 [2 4 6]]
